### ISSUE TITLE
Adicionar link de RSS

### ISSUE THREAD

**Issue by gmoura** [JS-ENV/jsenv-site#21]
Adicionar o link de RSS a sidebar

Link: http://jsenv.com/atom.xml

**Comment by wjsantos** [comment]
já há um link para rss no [código do master]

[código do master]: https://github.com/gmoura/jsenv/blob/master/source/_includes/custom/sidebar.html#L28

**Comment by gmoura** [comment]
Link adicionado ao menu de navegação
